/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import DAO.CaserneDAO;
import DAO.ConnexionBdd;
import DAO.EnginDAO;
import java.awt.Color;
import java.sql.Connection;
import modele.Caserne;
import modele.Compte;
import modele.Engin;
import modele.EnginType;

/**
 *
 * @author ts1sio
 */
public class AddEngin extends javax.swing.JFrame {
    
    Caserne laCaserne;
    Connection cnt;
    Compte leCompte;
    String laProvenance;

    /**
     * Creates new form Accueil
     */
    public AddEngin() {
        initComponents();
    }
    
    public AddEngin(Compte unCompte, Caserne uneCaserne, String uneProvenance) {
        initComponents();
        
        leCompte = unCompte;
        laCaserne = uneCaserne;
        laProvenance = uneProvenance;
        
    }

    AddEngin(Compte leCompte) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        messageError = new javax.swing.JLabel();
        enginTypeField = new javax.swing.JTextField();
        enginAddButton = new javax.swing.JButton();
        enginCaserne = new javax.swing.JTextField();
        enginType2 = new javax.swing.JLabel();
        enginName = new javax.swing.JTextField();
        enginType1 = new javax.swing.JLabel();
        enginType = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("RETOUR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/barre.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 720, 60));

        messageError.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        messageError.setForeground(new java.awt.Color(255, 204, 204));
        messageError.setText("MESSAGE");
        getContentPane().add(messageError, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 420, 30));

        enginTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginTypeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(enginTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 100, -1));

        enginAddButton.setText("Valider");
        enginAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginAddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enginAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        enginCaserne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginCaserneActionPerformed(evt);
            }
        });
        getContentPane().add(enginCaserne, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 100, -1));

        enginType2.setFont(new java.awt.Font("Reem Kufi", 0, 22)); // NOI18N
        enginType2.setForeground(new java.awt.Color(0, 0, 0));
        enginType2.setText("ID de caserne");
        getContentPane().add(enginType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 140, -1));

        enginName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginNameActionPerformed(evt);
            }
        });
        getContentPane().add(enginName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 100, -1));

        enginType1.setFont(new java.awt.Font("Reem Kufi", 0, 22)); // NOI18N
        enginType1.setForeground(new java.awt.Color(0, 0, 0));
        enginType1.setText("Engin libelle");
        getContentPane().add(enginType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 140, -1));

        enginType.setFont(new java.awt.Font("Reem Kufi", 0, 22)); // NOI18N
        enginType.setForeground(new java.awt.Color(0, 0, 0));
        enginType.setText("Engin type");
        getContentPane().add(enginType, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, -1));

        jLabel4.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("AJOUTER UN ENGIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/fond.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Engins(leCompte, laCaserne, laProvenance, "global").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enginAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginAddButtonActionPerformed
        
        messageError.setVisible(false);
        
        int type = Integer.valueOf(enginTypeField.getText());
        int caserne = Integer.valueOf(enginCaserne.getText());
        String libelle = enginName.getText();
        
        EnginType unType = new EnginType();
        unType.setId(type);
        
        Caserne uneCaserne = new Caserne();
        uneCaserne.setId(caserne);
        
        
        Engin unEngin = new Engin();
        unEngin.setLeTypeEngin(unType);
        unEngin.setLaCaserne(uneCaserne);
        unEngin.setLibelle(libelle);
        
        
        Connection cnt =  ConnexionBdd.ouvrirConnexion();
        int result = EnginDAO.AddEngin(cnt, unEngin);
        
        if(result == 1){
            messageError.setVisible(true);
            messageError.setText("Le véhicule a été inséré");
            messageError.setForeground(Color.green);
        }else{
            messageError.setVisible(true);
            messageError.setText("Le véhicule n'a pas été inséré");
            messageError.setForeground(Color.red);
        }
        
        
        
    }//GEN-LAST:event_enginAddButtonActionPerformed

    private void enginTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enginTypeFieldActionPerformed

    private void enginCaserneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginCaserneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enginCaserneActionPerformed

    private void enginNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enginNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEngin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEngin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEngin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEngin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEngin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enginAddButton;
    private javax.swing.JTextField enginCaserne;
    private javax.swing.JTextField enginName;
    private javax.swing.JLabel enginType;
    private javax.swing.JLabel enginType1;
    private javax.swing.JLabel enginType2;
    private javax.swing.JTextField enginTypeField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel messageError;
    // End of variables declaration//GEN-END:variables
}
