/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import DAO.CaserneDAO;
import DAO.ConnexionBdd;
import DAO.EnginDAO;
import DAO.EnginTypeDAO;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import modele.Caserne;
import modele.Compte;
import modele.Engin;
import modele.EnginType;

/**
 *
 * @author ts1sio
 */
public class AddTypeEngin extends javax.swing.JFrame {
    
    Caserne laCaserne;
    Connection cnt;
    Compte leCompte;
    String laProvenance;

    /**
     * Creates new form Accueil
     */
    public AddTypeEngin() {
        initComponents();
    }
    
    public AddTypeEngin(Compte unCompte, Caserne uneCaserne, String uneProvenance) {
        initComponents();
        
        leCompte = unCompte;
        laCaserne = uneCaserne;
        laProvenance = uneProvenance;
        
    }

    AddTypeEngin(Compte leCompte) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        messageError = new javax.swing.JLabel();
        enginAddButton = new javax.swing.JButton();
        enginName = new javax.swing.JTextField();
        enginType1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("RETOUR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/barre.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 720, 60));

        messageError.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        messageError.setForeground(new java.awt.Color(255, 204, 204));
        messageError.setText("MESSAGE");
        getContentPane().add(messageError, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 420, 30));

        enginAddButton.setText("Valider");
        enginAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginAddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enginAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        enginName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginNameActionPerformed(evt);
            }
        });
        getContentPane().add(enginName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 100, -1));

        enginType1.setFont(new java.awt.Font("Reem Kufi", 0, 22)); // NOI18N
        enginType1.setForeground(new java.awt.Color(0, 0, 0));
        enginType1.setText("Type libelle");
        getContentPane().add(enginType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 140, -1));

        jLabel4.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("AJOUTER UN ENGIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/fond.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Engins(leCompte, laCaserne, laProvenance).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enginAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginAddButtonActionPerformed
        
        messageError.setVisible(false);
        
        String libelle = enginName.getText();
             
        
        Connection cnt =  ConnexionBdd.ouvrirConnexion();
        int result = EnginTypeDAO.AddTypeEngin(cnt, libelle);
        
        if(result == 1){
            messageError.setVisible(true);
            messageError.setText("Le type a été enregistré");
            messageError.setForeground(Color.green);
            messageError.setFont(new Font(messageError.getName(), Font.PLAIN, 24));
        }else{
            messageError.setVisible(true);
            messageError.setText("Le type n'a pas été enregistré");
            messageError.setForeground(Color.red);
            messageError.setFont(new Font(messageError.getName(), Font.PLAIN, 24));
        }
        
        
        
    }//GEN-LAST:event_enginAddButtonActionPerformed

    private void enginNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enginNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTypeEngin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTypeEngin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTypeEngin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTypeEngin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTypeEngin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enginAddButton;
    private javax.swing.JTextField enginName;
    private javax.swing.JLabel enginType1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel messageError;
    // End of variables declaration//GEN-END:variables
}
