/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import DAO.CaserneDAO;
import DAO.ConnexionBdd;
import DAO.EnginDAO;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modele.Caserne;
import modele.Compte;
import modele.Engin;

/**
 *
 * @author ts1sio
 */
public class Engins extends javax.swing.JFrame {
    
    Caserne laCaserne;
    Connection cnt;
    Compte leCompte;
    String laProvenance;

    /**
     * Creates new form Accueil
     */
    public Engins() {
        initComponents();      
    }
    
    public Engins(Compte unCompte, Caserne uneCaserne, String uneProvenance, String recherche) {
        initComponents();
        
        leCompte = unCompte;
        laCaserne = uneCaserne;
        laProvenance = uneProvenance;
        
        
        Connection cnt =  ConnexionBdd.ouvrirConnexion();
        ArrayList<Engin> lesEngins;
        if(recherche.equals("caserne")){
            lesEngins = EnginDAO.getLesEngins(cnt);
        }else{
             lesEngins = EnginDAO.getLesEngins(cnt);
        }
       
        
        
        
        DefaultTableModel model =  new DefaultTableModel(new String[]{"ID", "TYPE", "CASERNE", "LIBELLE"}, 1);
        
        
        jTable1.setModel(model);
        for(int i = 0; i < lesEngins.size(); i++){
            Engin unEngin = lesEngins.get(i) ;
            model.addRow(new Object[] { String.valueOf(unEngin.getId()), unEngin.getLeTypeEngin().getId(), unEngin.getLaCaserne().getId(), unEngin.getLibelle()});

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        enginAddType = new javax.swing.JButton();
        enginAddEngin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("RETOUR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        enginAddType.setText("AJOUTER TYPE");
        enginAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginAddTypeActionPerformed(evt);
            }
        });
        getContentPane().add(enginAddType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 130, 40));

        enginAddEngin.setText("AJOUTER UN ENGIN");
        enginAddEngin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginAddEnginActionPerformed(evt);
            }
        });
        getContentPane().add(enginAddEngin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ENGIN TYPE", "CASERNE ID", "LIBELLE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 470));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/barre.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 720, 60));

        jLabel4.setFont(new java.awt.Font("Reem Kufi", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("ENGINS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/fond.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuAdmin(leCompte).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enginAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginAddTypeActionPerformed
        new AddTypeEngin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enginAddTypeActionPerformed

    private void enginAddEnginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginAddEnginActionPerformed
        new AddEngin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enginAddEnginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Engins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Engins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Engins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Engins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Engins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enginAddEngin;
    private javax.swing.JButton enginAddType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
